// FALSY quando um valor é considerado false e TRUTHY é considerado verdadeiro em contextos onde um boolean é obrigatório (condicionais e loops)

console.log('>> Exemplos de Falsy <<')
console.log(false ? "Verdadeiro" : "False")
console.log(0 ? "Verdadeiro" : "False")
console.log(-0 ? "Verdadeiro" : "False")
console.log("" ? "Verdadeiro" : "False")
console.log(null ? "Verdadeiro" : "False")
console.log(undefined ? "Verdadeiro" : "False")
console.log(NaN ? "Verdadeiro" : "False")

console.log('>> Exemplos de Truthy <<')
console.log(true ? "Verdadeiro" : "False")
console.log({} ? "Verdadeiro" : "False")
console.log(1 ? "Verdadeiro" : "False")
console.log(3.23 ? "Verdadeiro" : "False")
console.log("Vinício" ? "Verdadeiro" : "False")
console.log(" " ? "Verdadeiro" : "False")
console.log("0" ? "Verdadeiro" : "False")
console.log(-1 ? "Verdadeiro" : "False")
console.log(Infinity ? "Verdadeiro" : "False")
console.log(-Infinity ? "Verdadeiro" : "False")